In [1]:
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from misc import data_config, model_config

In [2]:
main_model_config = (
    model_config.query("main")
    .drop(columns="main")
    .rename(columns={k: f"model_{k}" for k in model_config.columns})
)

new_name = {
    "powermoe": "PowerMoE",
    "llamamoe": "LLaMA-MoE-v1",
    "olmoe": "OLMoE",
    "switch": "SwitchTransformers",
    "llamamoe2": "LLaMA-MoE-v2",
    "jetmoe": "JetMoE",
    "openmoe": "OpenMoE",
    "minicpm": "MiniCPM-MoE",
    "qwen": "Qwen1.5-MoE",
    "deepseek2": "DeepSeek-V2-Lite",
    "deepseek": "DeepSeekMoE",
    "xverse": "XVERSE-MoE",
    "qwen3": "Qwen3",
    "yuan": "Yuan2.0",
    "phi": "Phi-3.5-MoE",
    "grin": "GRIN-MoE",
    "mixtral": "Mixtral-8x7B",
    "jamba": "Jamba-Mini",
    "nllb": "NLLB-MoE",
    "qwen2": "Qwen2",
}

model_colors = {
    key: px.colors.qualitative.Dark24[i] for i, key in enumerate(main_model_config.index.values)
}

seg_lens = (4, 16, 64, 256)
seg_len_colors = {key: px.colors.qualitative.Plotly[i] for i, key in enumerate(seg_lens)}
main_model_config

,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
key,,,,,,,,
powermoe,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
llamamoe,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager
olmoe,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2
switch,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager
llamamoe2,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2
jetmoe,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2
openmoe,OpenMoE-8B,OP,causal,11.86,24,32,2,eager
minicpm,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2
qwen,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2
deepseek2,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2
deepseek,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2
xverse,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2
qwen3,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2
yuan,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2
phi,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2
grin,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2
mixtral,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2
jamba,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2
nllb,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager
qwen2,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2

In [3]:
main_data_config = data_config.rename(columns={k: f"data_{k}" for k in data_config.columns})
main_data_config

                   data_name data_abbr
key
c4                        C4        C4
cc2306           CommonCrawl        CC
book                   Books        BK
wikipedia          Wikipedia        WK
arxiv                  ArXiv        AX
stackexchange  StackExchange        SE
github                GitHub        GH

In [4]:
def make_abbr(df):
    return (
        f"{df["model_abbr"]}{"d" if df["is_decoder"] else "e"}"
        if df["model_type"] == "seq2seq"
        else df["model_abbr"]
    )

In [ ]:
root_dir = Path("../output/srp_mpq")

dfs = {
    p.stem: pd.merge(pd.read_parquet(p), main_model_config, left_on="model", right_index=True)
    for p in root_dir.glob("*.parquet")
}

for key in dfs.keys():
    if "dataset" in dfs[key].columns:
        dfs[key] = pd.merge(dfs[key], main_data_config, left_on="dataset", right_index=True)

for df in dfs.values():
    df["model"] = df["model"].astype(model_config.index.dtype)
    if "dataset" in df.columns:
        df["dataset"] = df["dataset"].astype(data_config.index.dtype)

sorted_model_keys = (
    dfs["mg"].query("is_decoder and seg_len == 16").sort_values("best_f1", ascending=False)["model"]
)

dfs["md"].query("seg_len == 16").pivot(
    index=["model", "is_decoder"], columns="dataset", values="best_f1"
)

dataset                     c4    cc2306      book  wikipedia     arxiv  \
model     is_decoder
powermoe  True        0.528772  0.527592  0.530765   0.546199  0.566806
llamamoe  True        0.450365  0.450565  0.448192   0.454389  0.454172
olmoe     True        0.455232  0.454706  0.455410   0.526970  0.535874
switch    False       0.168423  0.169951  0.166393   0.200539  0.202298
          True        0.163001  0.162464  0.164019   0.207586  0.199107
llamamoe2 True        0.809891  0.807653  0.811540   0.817960  0.793941
jetmoe    True        0.475049  0.474884  0.470432   0.480482  0.475177
openmoe   True        0.269967  0.275923  0.287056   0.280349  0.297329
minicpm   True        0.491174  0.490462  0.486214   0.497590  0.489688
qwen      True        0.308066  0.308014  0.301221   0.325069  0.305697
deepseek2 True        0.381817  0.379821  0.370162   0.382164  0.387526
deepseek  True        0.371197  0.370892  0.358760   0.370769  0.370943
xverse    True        0.384331  0.377736  0.370037   0.381811  0.378047
qwen3     True        0.542329  0.553316  0.584927   0.585007  0.561391
yuan      True        0.653304  0.649474  0.636344   0.680396  0.632825
phi       True        0.468310  0.470277  0.474483   0.518176  0.542557
grin      True        0.461833  0.465260  0.467894   0.521847  0.523523
mixtral   True        0.489905  0.490541  0.483831   0.494474  0.498267
jamba     True        0.371475  0.374259  0.370831   0.387589  0.385996
nllb      False       0.235108  0.236458  0.235773   0.247138  0.271155
          True        0.286624  0.287399  0.280328   0.340935  0.319238
qwen2     True        0.367747  0.368375  0.367396   0.373407  0.371282

dataset               stackexchange    github
model     is_decoder
powermoe  True             0.563160  0.563980
llamamoe  True             0.455140  0.456557
olmoe     True             0.550433  0.565604
switch    False            0.198313  0.209620
          True             0.196396  0.210864
llamamoe2 True             0.767787  0.763904
jetmoe    True             0.475215  0.470728
openmoe   True             0.288142  0.297447
minicpm   True             0.486447  0.483491
qwen      True             0.309131  0.303476
deepseek2 True             0.377972  0.370019
deepseek  True             0.369748  0.362639
xverse    True             0.392678  0.379447
qwen3     True             0.532862  0.552902
yuan      True             0.614251  0.598322
phi       True             0.562901  0.592005
grin      True             0.546484  0.573885
mixtral   True             0.497043  0.495310
jamba     True             0.385788  0.381558
nllb      False            0.257176  0.282331
          True             0.313202  0.328805
qwen2     True             0.366613  0.365654

In [6]:
sample_seg_len = 16

mdf = (
    pd.merge(
        dfs["mg"].drop(columns="best_m").rename(columns={"best_f1": "gen_best_f1"}),
        dfs["md"].drop(columns=["act_r", "best_m"]),
    )
    .query(f"seg_len == {sample_seg_len}")
    .drop(columns="seg_len")
)

mdf["f1_diff"] = (mdf["best_f1"] - mdf["gen_best_f1"]) / mdf["gen_best_f1"]
mdf.pivot(index=["model", "is_decoder"], columns="dataset", values="f1_diff")

dataset                     c4    cc2306      book  wikipedia     arxiv  \
model     is_decoder
powermoe  True       -0.033141 -0.035299 -0.029497  -0.001276  0.036403
llamamoe  True       -0.005282 -0.004840 -0.010081   0.003607  0.003126
olmoe     True       -0.092650 -0.093698 -0.092295   0.050337  0.068082
switch    False      -0.112603 -0.104557 -0.123303   0.056610  0.065876
          True       -0.137584 -0.140428 -0.132202   0.098309  0.053446
llamamoe2 True        0.017521  0.014710  0.019593   0.027659 -0.002518
jetmoe    True        0.001050  0.000703 -0.008678   0.012500  0.001322
openmoe   True       -0.054024 -0.033156  0.005856  -0.017647  0.041850
minicpm   True        0.003901  0.002447 -0.006236   0.017015  0.000865
qwen      True       -0.002217 -0.002384 -0.024386   0.052856 -0.009891
deepseek2 True        0.010336  0.005053 -0.020505   0.011253  0.025441
deepseek  True        0.009072  0.008243 -0.024738   0.007907  0.008380
xverse    True        0.010604 -0.006738 -0.026982   0.003978 -0.005919
qwen3     True       -0.029899 -0.010245  0.046300   0.046443  0.004199
yuan      True        0.024794  0.018786 -0.001811   0.067291 -0.007331
phi       True       -0.092214 -0.088401 -0.080249   0.004448  0.051709
grin      True       -0.086451 -0.079672 -0.074461   0.032262  0.035578
mixtral   True       -0.005748 -0.004455 -0.018073   0.003527  0.011223
jamba     True       -0.020238 -0.012896 -0.021937   0.022262  0.018059
nllb      False      -0.053477 -0.048042 -0.050800  -0.005042  0.091648
          True       -0.073559 -0.071054 -0.093907   0.101989  0.031857
qwen2     True       -0.002425 -0.000721 -0.003379   0.012929  0.007162

dataset               stackexchange    github
model     is_decoder
powermoe  True             0.029738  0.031237
llamamoe  True             0.005265  0.008394
olmoe     True             0.097101  0.127339
switch    False            0.044878  0.104455
          True             0.039102  0.115652
llamamoe2 True            -0.035377 -0.040255
jetmoe    True             0.001400 -0.008055
openmoe   True             0.009659  0.042265
minicpm   True            -0.005758 -0.011801
qwen      True             0.001232 -0.017081
deepseek2 True             0.000161 -0.020883
deepseek  True             0.005132 -0.014194
xverse    True             0.032553 -0.002239
qwen3     True            -0.046833 -0.010987
yuan      True            -0.036467 -0.061453
phi       True             0.091143  0.147560
grin      True             0.080997  0.135198
mixtral   True             0.008739  0.005224
jamba     True             0.017511  0.006354
nllb      False            0.035370  0.136639
          True             0.012348  0.062783
qwen2     True            -0.005501 -0.008103

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.005,
    vertical_spacing=0.1,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [16, 16, 18, 20]

for i, key in enumerate(sorted_model_keys):
    if (mdf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1

    for is_decoder in (False, True):
        tmpdf = mdf.query(f"model == '{key}' and is_decoder == {is_decoder}")
        if len(tmpdf) == 0:
            continue

        fig.add_bar(
            x=tmpdf["data_abbr"],
            y=tmpdf["f1_diff"],
            hoverinfo="skip",
            marker=go.bar.Marker(color=model_colors[key]),
            opacity=1 if is_decoder else 0.5,
            showlegend=False,
            row=row,
            col=col,
        )

    fig.update_xaxes(
        showticklabels=row == num_rows,
        tickangle=0,
        tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
        row=row,
        col=col,
    )

    fig.update_yaxes(showticklabels=col == 1, tickvals=[-0.1, 0, 0.1], row=row, col=col)

    if col == 1:
        fig.update_yaxes(
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            ticktext=["-10%", "SRP<br>(E,16)", "+10%"],
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=60, r=15, t=30, b=0), width=2000, height=400)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "msrpdd.pdf")
# fig.show()

In [8]:
sedf = dfs["ed"].query(f"seg_len == {sample_seg_len}").drop(columns="seg_len")
sedf

,model,is_decoder,layer_idx,expert_idx,dataset,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,data_name,data_abbr
1,powermoe,True,0,0,c4,0.694848,0.820701,1.423875,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,C4,C4
5,powermoe,True,0,0,cc2306,0.691056,0.818060,1.431446,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,CommonCrawl,CC
9,powermoe,True,0,0,book,0.646680,0.787783,1.486747,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,Books,BK
13,powermoe,True,0,0,wikipedia,0.563178,0.741508,1.563096,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,Wikipedia,WK
17,powermoe,True,0,0,arxiv,0.562731,0.729254,1.626349,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,ArXiv,AX
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
774125,qwen2,True,27,63,book,0.132557,0.335235,2.699352,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,Books,BK
774129,qwen2,True,27,63,wikipedia,0.128402,0.330493,2.649584,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,Wikipedia,WK
774133,qwen2,True,27,63,arxiv,0.130401,0.329264,2.655028,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,ArXiv,AX
774137,qwen2,True,27,63,stackexchange,0.129880,0.330160,2.666504,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,StackExchange,SE
774141,qwen2,True,27,63,github,0.129654,0.331546,2.651764,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,GitHub,GH

In [9]:
dsedf = (
    sedf.pivot(
        index=["model", "is_decoder", "layer_idx", "expert_idx"],
        columns="dataset",
        values="act_r",
    )
    .groupby("model", observed=True)
    .corr()
)

dsedf

dataset                       c4    cc2306      book  wikipedia     arxiv  \
model    dataset
powermoe c4             1.000000  0.978744  0.937798   0.729134  0.679949
         cc2306         0.978744  1.000000  0.929031   0.787864  0.670279
         book           0.937798  0.929031  1.000000   0.674666  0.604702
         wikipedia      0.729134  0.787864  0.674666   1.000000  0.609821
         arxiv          0.679949  0.670279  0.604702   0.609821  1.000000
...                          ...       ...       ...        ...       ...
qwen2    book           0.997815  0.997956  1.000000   0.993892  0.994540
         wikipedia      0.994632  0.994694  0.993892   1.000000  0.992196
         arxiv          0.996651  0.996603  0.994540   0.992196  1.000000
         stackexchange  0.997811  0.997513  0.995436   0.992662  0.997335
         github         0.995873  0.995659  0.993598   0.991678  0.996925

dataset                 stackexchange    github
model    dataset
powermoe c4                  0.686345  0.564100
         cc2306              0.663258  0.559120
         book                0.610619  0.488287
         wikipedia           0.557400  0.537901
         arxiv               0.914722  0.883749
...                               ...       ...
qwen2    book                0.995436  0.993598
         wikipedia           0.992662  0.991678
         arxiv               0.997335  0.996925
         stackexchange       1.000000  0.998279
         github              0.998279  1.000000

[140 rows x 7 columns]

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.005,
    vertical_spacing=0.1,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [16, 16, 18, 20]
show_scale = True

for i, key in enumerate(sorted_model_keys):
    if key not in dsedf.index.levels[0]:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = dsedf.loc[key]

    fig.add_heatmap(
        z=tmpdf.values,
        x=tmpdf.columns.map(main_data_config["data_abbr"]),
        y=tmpdf.index.map(main_data_config["data_abbr"]),
        colorbar=go.heatmap.ColorBar(tickfont=go.heatmap.colorbar.Tickfont(size=font_size[1])),
        colorscale="RdBu_r",
        hoverinfo="skip",
        zmin=-1,
        zmax=1,
        showscale=show_scale,
        row=row,
        col=col,
    )

    if row == num_rows:
        fig.update_xaxes(
            tickangle=0, tickfont=go.layout.xaxis.Tickfont(size=font_size[1]), row=row, col=col
        )

    if col == 1:
        fig.update_yaxes(tickfont=go.layout.yaxis.Tickfont(size=font_size[1]), row=row, col=col)

    show_scale = False

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=30, r=0, t=30, b=0), width=2000, height=400)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "plot/mactdr.pdf")
# fig.show()

In [11]:
csedf = (
    sedf.pivot(
        index=["model", "is_decoder", "layer_idx", "expert_idx"],
        columns="dataset",
        values="best_f1",
    )
    .groupby("model", observed=True)
    .corr()
)

csedf

dataset                       c4    cc2306      book  wikipedia     arxiv  \
model    dataset
powermoe c4             1.000000  0.978656  0.920813   0.778592  0.732542
         cc2306         0.978656  1.000000  0.927406   0.816800  0.728992
         book           0.920813  0.927406  1.000000   0.732665  0.678925
         wikipedia      0.778592  0.816800  0.732665   1.000000  0.645499
         arxiv          0.732542  0.728992  0.678925   0.645499  1.000000
...                          ...       ...       ...        ...       ...
qwen2    book           0.994956  0.995013  1.000000   0.981278  0.977251
         wikipedia      0.985063  0.986657  0.981278   1.000000  0.977938
         arxiv          0.982326  0.985333  0.977251   0.977938  1.000000
         stackexchange  0.989661  0.990875  0.985488   0.979151  0.990482
         github         0.982161  0.983024  0.975862   0.975690  0.987926

dataset                 stackexchange    github
model    dataset
powermoe c4                  0.745321  0.650831
         cc2306              0.722863  0.642793
         book                0.684056  0.587517
         wikipedia           0.608995  0.594913
         arxiv               0.909202  0.874565
...                               ...       ...
qwen2    book                0.985488  0.975862
         wikipedia           0.979151  0.975690
         arxiv               0.990482  0.987926
         stackexchange       1.000000  0.995971
         github              0.995971  1.000000

[140 rows x 7 columns]

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.005,
    vertical_spacing=0.1,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [16, 16, 18, 20]
show_scale = True

for i, key in enumerate(sorted_model_keys):
    if key not in csedf.index.levels[0]:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    tmpdf = csedf.loc[key]

    fig.add_heatmap(
        z=tmpdf.values,
        x=tmpdf.columns.map(main_data_config["data_abbr"]),
        y=tmpdf.index.map(main_data_config["data_abbr"]),
        colorbar=go.heatmap.ColorBar(tickfont=go.heatmap.colorbar.Tickfont(size=font_size[1])),
        colorscale="RdBu_r",
        hoverinfo="skip",
        zmin=-1,
        zmax=1,
        showscale=show_scale,
        row=row,
        col=col,
    )

    if row == num_rows:
        fig.update_xaxes(
            tickangle=0, tickfont=go.layout.xaxis.Tickfont(size=font_size[1]), row=row, col=col
        )

    if col == 1:
        fig.update_yaxes(tickfont=go.layout.yaxis.Tickfont(size=font_size[1]), row=row, col=col)

    show_scale = False

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))
fig.update_layout(margin=go.layout.Margin(l=30, r=0, t=30, b=0), width=2000, height=400)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "plot/msrpdr.pdf")
# fig.show()