In [1]:
from pathlib import Path

import pandas as pd

from misc import model_config

In [2]:
cmp_groups = {
    "llamamoe": {"llamamoe", "llamamoes"},
    "olmoe": {"olmoe", "olmoesft", "olmoedpo", "olmoeins"},
    "jetmoe": {"jetmoe", "jetmoesft", "jetmoechat"},
}

cmp_keys = [v for vs in cmp_groups.values() for v in vs]

cmp_model_config = (
    model_config.loc[cmp_keys]
    .drop(columns="main")
    .rename(columns={k: f"model_{k}" for k in model_config.columns})
)

for k, vs in cmp_groups.items():
    for v in vs:
        cmp_model_config.loc[v, "model_group"] = k

cmp_model_config["model_group"] = cmp_model_config["model_group"].astype(model_config.index.dtype)
cmp_model_config

,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,model_group
key,,,,,,,,,
llamamoes,LLaMA-MoE-v1-3.5B-SFT,LL1-S,causal,6.74,32,16,4,eager,llamamoe
llamamoe,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
olmoedpo,OLMoE-1B-7B-0125-DPO,OL-D,causal,6.92,16,64,8,flash_attention_2,olmoe
olmoe,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2,olmoe
olmoeins,OLMoE-1B-7B-0125-Instruct,OL-I,causal,6.92,16,64,8,flash_attention_2,olmoe
olmoesft,OLMoE-1B-7B-0125-SFT,OL-S,causal,6.92,16,64,8,flash_attention_2,olmoe
jetmoe,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2,jetmoe
jetmoesft,JetMoE-8B-SFT,JT-S,causal,8.52,24,8,2,flash_attention_2,jetmoe
jetmoechat,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe

In [ ]:
root_dir1 = Path("../output/srp_mpq")

dfs1 = {
    p.stem: pd.merge(pd.read_parquet(p), cmp_model_config, left_on="model", right_index=True)
    for p in root_dir1.glob("*.parquet")
}

for df in dfs1.values():
    df["model"] = df["model"].astype(model_config.index.dtype)

dfs1["mg"].pivot(index=["model_group", "model_name"], columns="seg_len", values=["best_f1", "best_m"])

                                        best_f1                                \
seg_len                                     4         16        64        256
model_group model_name
llamamoe    LLaMA-MoE-v1-3.5B          0.558514  0.452756  0.415262  0.405520
            LLaMA-MoE-v1-3.5B-SFT      0.558451  0.452615  0.415136  0.405484
olmoe       OLMoE-1B-7B-0125           0.641371  0.501716  0.446431  0.416328
            OLMoE-1B-7B-0125-DPO       0.644241  0.505251  0.450462  0.421314
            OLMoE-1B-7B-0125-Instruct  0.644045  0.504979  0.450182  0.421019
            OLMoE-1B-7B-0125-SFT       0.644594  0.505859  0.451173  0.422089
jetmoe      JetMoE-8B                  0.603128  0.474550  0.426860  0.410136
            JetMoE-8B-Chat             0.601316  0.473328  0.425848  0.409489
            JetMoE-8B-SFT              0.601277  0.473275  0.425788  0.409440

                                         best_m
seg_len                                     4         16        64        256
model_group model_name
llamamoe    LLaMA-MoE-v1-3.5B          1.029958  2.389879  2.941798  3.573369
            LLaMA-MoE-v1-3.5B-SFT      1.029288  2.389273  2.942530  3.573040
olmoe       OLMoE-1B-7B-0125           0.994973  1.053159  1.198923  1.215971
            OLMoE-1B-7B-0125-DPO       0.998438  1.059491  1.210503  1.233400
            OLMoE-1B-7B-0125-Instruct  0.998128  1.058784  1.209494  1.232083
            OLMoE-1B-7B-0125-SFT       0.998741  1.059345  1.209073  1.186965
jetmoe      JetMoE-8B                  1.093049  2.254469  2.696328  3.183836
            JetMoE-8B-Chat             1.090746  2.259711  2.709022  3.206929
            JetMoE-8B-SFT              1.090716  2.260014  2.710049  3.209081

In [ ]:
root_dir2 = Path("../output/sch_mpq")

dfs2 = {
    p.stem: pd.merge(pd.read_parquet(p), cmp_model_config, left_on="model", right_index=True)
    for p in root_dir2.glob("*.parquet")
}

for df in dfs2.values():
    df["model"] = df["model"].astype(model_config.index.dtype)

dfs2["m"]

,model,is_decoder,dataset,seg_len,cache_m,recall,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,model_group
35840,llamamoe,True,c4,4,0.007812,0.006907,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
35841,llamamoe,True,c4,4,0.015625,0.013401,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
35842,llamamoe,True,c4,4,0.023438,0.019668,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
35843,llamamoe,True,c4,4,0.031250,0.025783,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
35844,llamamoe,True,c4,4,0.039062,0.031782,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager,llamamoe
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
246395,jetmoechat,True,github,256,3.916667,0.988994,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe
246396,jetmoechat,True,github,256,3.937500,0.992001,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe
246397,jetmoechat,True,github,256,3.958333,0.994884,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe
246398,jetmoechat,True,github,256,3.979167,0.997592,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe
246399,jetmoechat,True,github,256,4.000000,1.000000,JetMoE-8B-Chat,JT-C,causal,8.52,24,8,2,flash_attention_2,jetmoe