In [1]:
from pathlib import Path

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
from plotly.subplots import make_subplots

from misc import model_config

In [2]:
main_model_config = (
    model_config.query("main")
    .drop(columns="main")
    .rename(columns={k: f"model_{k}" for k in model_config.columns})
)

new_name = {
    "powermoe": "PowerMoE",
    "llamamoe": "LLaMA-MoE-v1",
    "olmoe": "OLMoE",
    "switch": "SwitchTransformers",
    "llamamoe2": "LLaMA-MoE-v2",
    "jetmoe": "JetMoE",
    "openmoe": "OpenMoE",
    "minicpm": "MiniCPM-MoE",
    "qwen": "Qwen1.5-MoE",
    "deepseek2": "DeepSeek-V2-Lite",
    "deepseek": "DeepSeekMoE",
    "xverse": "XVERSE-MoE",
    "qwen3": "Qwen3",
    "yuan": "Yuan2.0",
    "phi": "Phi-3.5-MoE",
    "grin": "GRIN-MoE",
    "mixtral": "Mixtral-8x7B",
    "jamba": "Jamba-Mini",
    "nllb": "NLLB-MoE",
    "qwen2": "Qwen2",
}

model_colors = {
    key: px.colors.qualitative.Dark24[i] for i, key in enumerate(main_model_config.index.values)
}

seg_lens = (4, 16, 64, 256)
seg_len_colors = {key: px.colors.qualitative.Plotly[i] for i, key in enumerate(seg_lens)}
main_model_config

,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
key,,,,,,,,
powermoe,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
llamamoe,LLaMA-MoE-v1-3.5B,LL1,causal,6.74,32,16,4,eager
olmoe,OLMoE-1B-7B-0125,OL,causal,6.92,16,64,8,flash_attention_2
switch,SwitchTransformers-Base-128,ST,seq2seq,7.42,24,128,1,eager
llamamoe2,LLaMA-MoE-v2-3.8B,LL2,causal,8.03,32,8,2,flash_attention_2
jetmoe,JetMoE-8B,JT,causal,8.52,24,8,2,flash_attention_2
openmoe,OpenMoE-8B,OP,causal,11.86,24,32,2,eager
minicpm,MiniCPM-MoE-8x2B,MC,causal,13.87,40,8,2,flash_attention_2
qwen,Qwen1.5-MoE-A2.7B,QW1,causal,14.32,24,60,4,flash_attention_2
deepseek2,DeepSeek-V2-Lite,DS2,causal,15.71,27,64,6,flash_attention_2
deepseek,DeepSeekMoE,DS1,causal,16.38,28,64,6,flash_attention_2
xverse,XVERSE-MoE-A4.2B,XV,causal,25.78,28,64,6,flash_attention_2
qwen3,Qwen3-30B-A3B,QW3,causal,30.53,48,128,8,flash_attention_2
yuan,Yuan2.0-M32,Y2,causal,39.94,24,32,2,flash_attention_2
phi,Phi-3.5-MoE,PH,causal,41.87,32,16,2,flash_attention_2
grin,GRIN-MoE,GR,causal,41.87,32,16,2,flash_attention_2
mixtral,Mixtral-8x7B-v0.1,MX,causal,46.70,32,8,2,flash_attention_2
jamba,Jamba-Mini-1.6,JB,causal,51.57,32,16,2,flash_attention_2
nllb,NLLB-MoE-54B,NL,seq2seq,54.50,48,128,2,eager
qwen2,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2

In [3]:
def make_abbr(df):
    return (
        f"{df["model_abbr"]}{"d" if df["is_decoder"] else "e"}"
        if df["model_type"] == "seq2seq"
        else df["model_abbr"]
    )

In [ ]:
root_dir = Path("../output/srp_pos_mpq")

dfs = {
    p.stem: pd.merge(pd.read_parquet(p), main_model_config, left_on="model", right_index=True)
    for p in root_dir.glob("*.parquet")
}

for df in dfs.values():
    df["model"] = df["model"].astype(model_config.index.dtype)

dfs["mg"]

,model,is_decoder,seg_len,start_pos,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn
0,powermoe,True,4,0,0.200,0.615347,1.023793,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
1,powermoe,True,4,1,0.200,0.665613,1.085777,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
2,powermoe,True,4,2,0.200,0.670400,1.092818,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
3,powermoe,True,4,3,0.200,0.671855,1.093903,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
4,powermoe,True,4,4,0.200,0.672332,1.096399,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48045,qwen2,True,256,252,0.125,0.275016,2.526532,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
48046,qwen2,True,256,253,0.125,0.275013,2.526528,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
48047,qwen2,True,256,254,0.125,0.275012,2.526484,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
48048,qwen2,True,256,255,0.125,0.275015,2.526577,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2
48049,qwen2,True,256,256,0.125,0.275014,2.526366,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2

In [5]:
smgdf = (
    dfs["mg"]
    .groupby(["model", "is_decoder", "seg_len"], as_index=False, observed=True)[["best_f1"]]
    .std()
)

smgdf.pivot(index=["model", "is_decoder"], columns="seg_len", values="best_f1")

seg_len                    4         16        64        256
model     is_decoder
powermoe  True        0.002496  0.000763  0.000356  0.000107
llamamoe  True        0.002137  0.001087  0.000524  0.000160
olmoe     True        0.004468  0.005314  0.004702  0.002358
switch    False       0.002587  0.003213  0.002207  0.000719
          True        0.013662  0.009297  0.000840       NaN
llamamoe2 True        0.006909  0.004102  0.001926  0.000869
jetmoe    True        0.001717  0.001491  0.001152  0.000458
openmoe   True        0.006817  0.014200  0.009396  0.004138
minicpm   True        0.001940  0.001570  0.001241  0.000499
qwen      True        0.001876  0.003461  0.002904  0.001343
deepseek2 True        0.005712  0.006228  0.004935  0.002630
deepseek  True        0.004936  0.004532  0.004411  0.002147
xverse    True        0.007722  0.007997  0.006028  0.003049
qwen3     True        0.006948  0.004227  0.003325  0.001616
yuan      True        0.003370  0.001083  0.000554  0.000315
phi       True        0.004543  0.001969  0.000897  0.000396
grin      True        0.004207  0.001593  0.001051  0.000546
mixtral   True        0.000614  0.000566  0.000589  0.000251
jamba     True        0.006305  0.005976  0.004255  0.002337
nllb      False       0.008869  0.003783  0.012395  0.017016
          True        0.003484  0.014549  0.018281  0.016084
qwen2     True        0.003660  0.001082  0.000175  0.000186

In [ ]:
sample_seg_len = 16

smddf = (
    dfs["md"]
    .query(f"seg_len == {sample_seg_len}")
    .drop(columns="seg_len")
    .groupby(["model", "is_decoder", "dataset"], as_index=False, observed=True)[["best_f1"]]
    .std()
)

smddf.pivot(index=["model", "is_decoder"], columns="dataset", values="best_f1")

dataset                     c4    cc2306      book  wikipedia     arxiv  \
model     is_decoder
powermoe  True        0.000962  0.000894  0.000945   0.000931  0.001202
llamamoe  True        0.000784  0.000811  0.000856   0.000950  0.001065
olmoe     True        0.001936  0.001909  0.002129   0.002130  0.009202
switch    False       0.002670  0.002880  0.003012   0.004250  0.003537
          True        0.011998  0.011939  0.012141   0.007719  0.008127
llamamoe2 True        0.004573  0.004275  0.004853   0.002754  0.004945
jetmoe    True        0.000857  0.000813  0.001045   0.001840  0.001525
openmoe   True        0.015577  0.014170  0.013227   0.011982  0.016763
minicpm   True        0.000858  0.000973  0.001209   0.001851  0.001937
qwen      True        0.001428  0.002061  0.002060   0.003159  0.004384
deepseek2 True        0.002711  0.002686  0.002009   0.004577  0.009264
deepseek  True        0.001876  0.001802  0.002007   0.003408  0.006698
xverse    True        0.003828  0.004240  0.003231   0.005539  0.008726
qwen3     True        0.003320  0.003256  0.004211   0.003171  0.006121
yuan      True        0.001459  0.001245  0.001619   0.001604  0.001876
phi       True        0.002551  0.002380  0.003361   0.001780  0.002786
grin      True        0.002351  0.002288  0.003348   0.001581  0.004440
mixtral   True        0.000642  0.000472  0.000450   0.000452  0.000870
jamba     True        0.002605  0.003132  0.003089   0.007885  0.005952
nllb      False       0.001988  0.002289  0.002366   0.005201  0.006812
          True        0.014629  0.014273  0.017007   0.018826  0.013515
qwen2     True        0.000608  0.000673  0.000674   0.001515  0.001570

dataset               stackexchange    github
model     is_decoder
powermoe  True             0.000969  0.001341
llamamoe  True             0.001368  0.002167
olmoe     True             0.007762  0.014043
switch    False            0.003223  0.003628
          True             0.008674  0.007738
llamamoe2 True             0.003722  0.004105
jetmoe    True             0.001649  0.003165
openmoe   True             0.014949  0.013020
minicpm   True             0.001738  0.002963
qwen      True             0.004701  0.006945
deepseek2 True             0.008251  0.013087
deepseek  True             0.006784  0.011656
xverse    True             0.011651  0.017554
qwen3     True             0.007841  0.011022
yuan      True             0.001453  0.001252
phi       True             0.002077  0.002993
grin      True             0.002923  0.006316
mixtral   True             0.000837  0.001509
jamba     True             0.008270  0.009789
nllb      False            0.004823  0.006757
          True             0.012026  0.016150
qwen2     True             0.001270  0.001887

In [ ]:
sorted_model_keys = (
    pd.merge(
        pd.read_parquet("../output/srp_mpq/mg.parquet"),
        main_model_config,
        left_on="model",
        right_index=True,
    )
    .query("is_decoder and seg_len == 16")
    .sort_values("best_f1", ascending=False)["model"]
)

sorted_model_keys

36     llamamoe2
84          yuan
80         qwen3
1       powermoe
88           phi
92          grin
13         olmoe
96       mixtral
60       minicpm
44        jetmoe
5       llamamoe
76        xverse
100        jamba
68     deepseek2
112        qwen2
72      deepseek
108         nllb
64          qwen
56       openmoe
33        switch
Name: model, dtype: category
Categories (27, object): ['powermoe' < 'llamamoe' < 'llamamoes' < 'olmoe' ... 'mixtral' < 'jamba' < 'nllb' < 'qwen2']

In [22]:
mgdf = (
    dfs["mg"]
    .assign(seg_pos=dfs["mg"]["start_pos"] + dfs["mg"]["seg_len"] // 2)
    .drop(columns="start_pos")
)

mgdf

,model,is_decoder,seg_len,act_r,best_f1,best_m,model_name,model_abbr,model_type,model_num_params,model_num_layers,model_num_experts,model_top_k,model_attn,seg_pos
0,powermoe,True,4,0.200,0.615347,1.023793,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,2
1,powermoe,True,4,0.200,0.665613,1.085777,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,3
2,powermoe,True,4,0.200,0.670400,1.092818,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,4
3,powermoe,True,4,0.200,0.671855,1.093903,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,5
4,powermoe,True,4,0.200,0.672332,1.096399,PowerMoE-3B,PW,causal,3.30,32,40,8,flash_attention_2,6
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48045,qwen2,True,256,0.125,0.275016,2.526532,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,380
48046,qwen2,True,256,0.125,0.275013,2.526528,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,381
48047,qwen2,True,256,0.125,0.275012,2.526484,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,382
48048,qwen2,True,256,0.125,0.275015,2.526577,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,383
48049,qwen2,True,256,0.125,0.275014,2.526366,Qwen2-57B-A14B,QW2,causal,57.41,28,64,8,flash_attention_2,384

In [ ]:
num_cols = 10
num_rows = (len(main_model_config) - 1) // num_cols + 1

fig = make_subplots(
    rows=num_rows,
    cols=num_cols,
    shared_xaxes="all",
    shared_yaxes="all",
    horizontal_spacing=0.005,
    vertical_spacing=0.11,
    subplot_titles=sorted_model_keys.map(new_name).values,
)

font_size = [16, 16, 18, 20]
show_legend = True

for i, key in enumerate(sorted_model_keys):
    if (mgdf["model"] == key).sum() == 0:
        continue

    row = i // num_cols + 1
    col = i % num_cols + 1
    num_layers = model_config.loc[key, "num_layers"]

    for seg_len in seg_lens:
        tmpdf = mgdf.query(f"model == '{key}' and seg_len == {seg_len}")
        if len(tmpdf) == 0:
            continue

        line_name = f"SRP(E,{seg_len})"

        if main_model_config.loc[key, "model_type"] == "seq2seq":
            for is_decoder in (False, True):
                subdf = tmpdf.query(f"is_decoder == {is_decoder}")
                if len(subdf) == 0:
                    continue

                fig.add_scatter(
                    x=subdf["seg_pos"],
                    y=subdf["best_f1"],
                    hoverinfo="skip",
                    legendgroup=line_name,
                    line=go.scatter.Line(
                        color=seg_len_colors[seg_len], dash="solid" if is_decoder else "dot"
                    ),
                    mode="lines",
                    name=line_name,
                    opacity=1 if is_decoder else 0.5,
                    showlegend=show_legend,
                    row=row,
                    col=col,
                )
        else:
            fig.add_scatter(
                x=tmpdf["seg_pos"],
                y=tmpdf["best_f1"],
                hoverinfo="skip",
                legendgroup=line_name,
                line=go.scatter.Line(color=seg_len_colors[seg_len]),
                mode="lines",
                name=line_name,
                showlegend=show_legend,
                row=row,
                col=col,
            )

    show_legend = False

    fig.update_xaxes(
        showticklabels=True,
        tickfont=go.layout.xaxis.Tickfont(size=font_size[1]),
        row=row,
        col=col,
    )

    if row == num_rows:
        fig.update_xaxes(
            title=go.layout.xaxis.Title(
                font=go.layout.xaxis.title.Font(size=font_size[2]), standoff=1, text="Position"
            ),
            row=row,
            col=col,
        )

    fig.update_yaxes(showticklabels=col == 1, row=row, col=col)

    if col == 1:
        fig.update_yaxes(
            tickfont=go.layout.yaxis.Tickfont(size=font_size[1]),
            title=go.layout.yaxis.Title(
                font=go.layout.yaxis.title.Font(size=font_size[2]), text="SRP(E,m)"
            ),
            row=row,
            col=col,
        )

fig.update_annotations(font=go.layout.annotation.Font(size=font_size[3]))

fig.update_layout(
    legend=go.layout.Legend(
        font=go.layout.legend.Font(size=font_size[2]), orientation="h", x=0.47, xanchor="center"
    ),
    margin=go.layout.Margin(l=60, r=0, t=30, b=0),
    width=2000,
    height=500,
)

plot_dir = Path("../plot")
plot_dir.mkdir(parents=True, exist_ok=True)
fig.write_image(plot_dir / "msrpp.pdf")
# fig.show()